---
deployment:
  tasks:
    - cd ../../cpanelgithubdemo.pratikwadekar.me/ && rm *.js && rm *.html && rm *.css && rm *.txt && rm *.ico && rm -r assets
    - /bin/cp -R ../repositories/cpanelgithubdemo/dist/cpanelgithubdemo/* ../../../../home/pratiqpd/cpanelgithubdemo.pratikwadekar.me
