---
deployment:
  tasks:
    - /bin/rm ../../cpanelgithubdemo/* 
    - /bin/cp -R /home/pratiqpd/repositories/cpanelgithubdemo/dist/cpanelgithubdemo/* /home/pratiqpd/cpanelgithubdemo.pratikwadekar.me
