---
deployment:
  tasks:
    - /bin/cp -R /home/repositories/cpanelgithubdemo/dist/cpanelgithubdemo/* /home/pratiqpd/cpanelgithubdemo.pratikwadekar.me
    - /bin/rm -f /home/pratiqpd/cpanelgithubdemo.pratikwadekar.me/* 
    
